### ISSUE TITLE
スライダー横のReplaceボタン

### ISSUE THREAD

**Issue by Riki4649** [kafuji/Sakura_Poselib#11]
間違って押しちゃう気がするので確認ダイアログを表示するなどしてワンクッション置くか
もしくはApplyボタンのほうが嬉しいです。ポーズをパカパカ切り替えるのに
便利なアドオンありがとう

**Comment by kafuji** [comment]
ご提案ありがとうございます。
ご指摘の通り誤操作のおそれがありますが、項目を選択せずに素早くポーズ上書きするために役立つので、
プリファレンスで表示ボタンのON/OFFをカスタマイズできるようにしようと思います。

**Comment by kafuji** [comment]
追記：Apply/Replace/Select Used Bones あたりの操作を任意で並べられるようにしようと思います。

**Comment by kafuji** [comment]
大変遅くなりましたがプリファレンスにポーズリスト上の表示設定を追加し、そのクイックアクセスボタンをポーズリストパネルの上に表示することで対応しました。
